# -*- coding: utf-8 -*-
"""RAG-Based Customer Support Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYz-ocBTugRL-cECZd4u5n4_3fON2PNd
"""

#STEP 1: Install Libraries
!pip install langchain langgraph chromadb pypdf sentence-transformers openai tiktoken

#STEP 2: Upload Your PDF

from google.colab import files
uploaded = files.upload()

STEP 3: Set API Key

import os
os.environ["OPENAI_API_KEY"] = "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"

!pip install -U langchain langchain-community langchain-openai langgraph chromadb pypdf sentence-transformers tiktoken

import langchain_community
print("Installed successfully!")

STEP 4: Load PDF

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("support_docs.pdf")
docs = loader.load()

print("Loaded documents:", len(docs))

!pip install langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = splitter.split_documents(docs)

print("Chunks created:", len(chunks))

STEP 5: Chunk Documents

#step6
!pip install sentence-transformers

STEP 6: Create Embeddings + ChromaDB

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

embedding = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

db = Chroma.from_documents(
    documents=chunks,
    embedding=embedding
)

print("DB created using FREE embeddings")

STEP 7: Retriever

#step-7
retriever = db.as_retriever()

docs_test = retriever.invoke("refund policy")
print("Docs fetched:", len(docs_test))

!pip install transformers

STEP 8: LLM Setup

from transformers import pipeline

generator = pipeline("text-generation", model="distilgpt2")

def simple_llm(prompt):
    result = generator(prompt, max_length=200, num_return_sequences=1)
    return result[0]['generated_text']

STEP 9: Routing Logic

def route_query(context, query):
    if not context or len(context.strip()) < 50:
        return "escalate"

    if "complaint" in query.lower():
        return "escalate"

    return "answer"

STEP 10: HITL Function

def human_escalation(query):
    print("\n⚠️ Escalated to Human Agent")
    print("Query:", query)
    return input("Enter human response: ")

STEP 11: LangGraph Workflow

from langgraph.graph import StateGraph
from typing import TypedDict

class GraphState(TypedDict):
    query: str
    context: str
    decision: str
    answer: str

def process_node(state):
    decision = route_query(state["context"], state["query"])
    return {**state, "decision": decision}

def answer_node(state):
    prompt = f"""
Context:
{state['context']}

Question:
{state['query']}

Answer clearly.
"""
    response = llm.invoke(prompt)
    return {**state, "answer": response.content}

def hitl_node(state):
    answer = human_escalation(state["query"])
    return {**state, "answer": answer}

builder = StateGraph(GraphState)

builder.add_node("process", process_node)
builder.add_node("answer", answer_node)
builder.add_node("hitl", hitl_node)

builder.set_entry_point("process")

builder.add_conditional_edges(
    "process",
    lambda state: state["decision"],
    {
        "answer": "answer",
        "escalate": "hitl"
    }
)

builder.set_finish_point("answer")
builder.set_finish_point("hitl")

graph = builder.compile()

STEP 12: Query Execution

def ask(query):
    docs = retriever.invoke(query)
    context = "\n".join([d.page_content for d in docs])

    decision = route_query(context, query)

    if decision == "escalate":
        answer = human_escalation(query)
    else:
        prompt = f"""
        Context:
        {context}

        Question:
        {query}

        Answer:
        """
        answer = simple_llm(prompt)

    print("\n💬 Answer:")
    print(answer)

STEP 13: Test Your System

ask("What is refund policy?")

ask("I want to file a complaint")

#####DONE####